### ISSUE TITLE
testing sandbox

### ISSUE THREAD

**Issue by arthurtalkgoal** [chloerei/alipay#13]
I found that alipay sand box should go   'https://openapi.alipaydev.com/gateway.do?'
and live is 'https://mapi.alipay.com/gateway.do?'

I tried to update the test url. 
However, I don't know how to generate the API info.

Can I ask how can you get the API　partner, key and signature for alipay sandobx?
(I created a sandbox acct but seems not able to generate the API　key
https://sandbox.alipaydev.com)

**Comment by chloerei** [comment]
Sorry for so long to reply, Alipay api is very confusion that I'm not fully know it.

Alipay have three gateway:

### 1 https://mapi.alipay.com/gateway.do

Major Web API, for website payment.

Doc: https://b.alipay.com/order/techService.htm

### 2 https://wappaygw.alipay.com

Like 1, but special for Wap API.

Doc: https://b.alipay.com/order/techService.htm

### 3 https://openapi.alipaydev.com/gateway.do 

Alipay open platform, I'm not clear when to use it.

Doc: https://openhome.alipay.com/doc/docIndex.htm

This gem current cover 1 / 2, but not 3. Sand box looks is only support 3, not 1 / 2.

Alipay partner, key is registered in https://b.alipay.com/newIndex.htm .
