### ISSUE TITLE
支付宝是否没有“确认收货”接口？

### ISSUE THREAD

**Issue by JeskTop** [chloerei/alipay#17]
我看文档中，这个gem并没有提供“确认收货”的接口，后面想着可以自己实现，然后提交到gem中，后面找了一遍文档也没有发现对应的接口。
难道说“担保交易”真的没有提供这样的接口？如果不走到支付宝页面手动点击“确认收货”的话，就只能等待自动结算了？

**Comment by chloerei** [comment]
是的，担保交易没有确认收货接口，并且这个是要买方确认的，只能等待确认或者自动结算。
