### ISSUE TITLE
alipay 0.6.0 里程碑和 alipay-demo 项目

### ISSUE THREAD

**Issue by chloerei** [chloerei/alipay#26]
不知不觉，从 alipay [v0.0.1](https://github.com/chloerei/alipay/releases/tag/v0.0.1) 发布至今已经过去一年半了。一开始这个 gem 只有担保交易和确认发货两个接口，在[多人的贡献](https://github.com/chloerei/alipay/graphs/contributors)下，alipay 支持越来越多的接口。

逐渐这个项目有点难维护了：

1. 代码开始凌乱。
2. alipay 接口本身是个黑箱，需要在线调试才能确定某个接口行为是否符合预期。
3. 每个人都只有部分访问权限，只能确认自己用到的部分是否工作正常（包括我）。
4. 开发阶段用生产应用做测试太繁重了。

所以我在 0.6.0.beta1 进行了一些改进：

1. 重构去除一些重复代码。主要是 Sign 部分，预留了 RSA 和 DSA 加密，添加了 verify_rsa? 验证，详情请看 CHANGELOG。
2. 把测试库升级为 Minitest，并且把某些测试用例固化成字符串。
3. 开发了 alipay-demo 项目，详情在后面介绍。

### alipay-demo

项目地址： https://github.com/chloerei/alipay-demo

这个是个 Rails app，它有两个目的，一是演示 alipay gem 的用法，二是供 gem 的开发者测试。它为 heroku 部署做了优化，可以免费部署到 heroku 做在线调试。你可以查看项目的 README，或者 Heroku 的文档了解如何部署 Rails app https://devcenter.heroku.com/articles/getting-started-with-rails4 。

目前它只有担保交易和确认发货的示例，因为我只有这两个接口的访问权限。欢迎其它接口的贡献者也为这个项目添加接口的示例，这样以后调试的时候就不用部署测试环境的生产应用了（当然最终更新 gem 到生产环境前还是应该先用真实应用测试）。

贡献示例请按照以下准则：

1. 最小可行的示例，不需要太复杂的场景（现有示例甚至没有用数据库）。
2. 一个接口一个示例既可，优先完善现有示例，如果一个接口有多种用途则例外。
3. 参考现有示例。

提交按照一般的 PR 流程既可。友情提示：当在调试 alipay gem 的时候，可以创建一个 alipay-demo 分支，更新 Gemfile 指向自己的的 alipay branch 用作测试。

### 0.6.0 TODO

我计划中为了发布 0.6.0 还需要完成：

1. 测试反馈，我不知道我没有权限访问的接口是否有被重构搞坏。
2. 改进文档和注释。alipay 的接口名不标注中文可能根本看不懂含义，但是我希望这个 gem 能为 Ruby 开发者所用而不仅仅是 Ruby 中文开发者，所以需要一种合适的注释格式。
3. 添加 RSA 和 DSA 加密/验证。

希望 alipay gem 的贡献者和使用者提供反馈，集成支付宝的过程很痛苦，一个良好维护的 gem 能让痛苦来得轻一点。

**Comment by 85636682** [comment]
@chloerei 可以的话，结合app客户端的网页支付部分!

**Comment by zlx** [comment]
+1
