### ISSUE TITLE
文件组织方式改进

### ISSUE THREAD

**Issue by jasl** [chloerei/alipay#29]
我在尝试将过去为alipay打的补丁合并到最新的开发版本当中，其中实现了

- RSA方式的签名
- 移动APP的支付API
- 用于移动端的风险探测接口（在移动端必须提前调用否则支付存在额度限制）

结合支付宝的API文档和通过浏览最近版本的代码，有一点想讨论：
以平台的方式组织文件，而不是用途，是不是更好一些？简单的说就是`wap`目录中存放`sign.rb`, `notify.rb`, `service.rb`，这样属于wap平台的API和相关函数在同一命名空间下，同理App平台的相关函数。

签名算法放入`sign`目录，即`Sign`命名空间，然后不同的算法单独文件保存，如 `Alipay::Sign::Md5` 且只包含 `generate`和`verify?`两个方法，因为不同平台的API的`params_to_string`的算法有可能是不同的，就交给不同平台的`sign.rb`去处理

我认为这样处理的话会更清晰，而且容易修改，看看大伙有什么看法，我来考虑如何移植代码

**Comment by chloerei** [comment]
我觉得不错。 cc @HungYuHei

**Comment by chloerei** [comment]
移动APP的支付API 和 用于移动端的风险探测接口 是属于哪个 GATEWAY_URL 的？

**Comment by jasl** [comment]
放到最外层的`service.rb`更合适，其中 `terminal_type` 可选 `web`，`wap`和`mobile`
文档在 <https://openhome.alipay.com/doc/viewApiDoc.htm?name=alipay.security.risk.detect&version=1.0&subVersion=1.0&packageCode=SECURITY> 
需要注意的是，这个字段我们使用大写的方式调用（生产环境实测），但是文档中给的小写

**Comment by HungYuHei** [comment]
我也觉得按平台来分会更好，因为支付宝不同平台的差别太多了

**Comment by jasl** [comment]
@HungYuHei @chloerei 所以我先按照这个模式来重构，然后你们来review吧

**Comment by chloerei** [comment]
@jasl 好，模块结构就按这个改。先 PR 模块重构，再添加功能，分开进行。

alipay.security.risk.detect 我看代码示例网关是 https://openapi.alipay.com/gateway.do ？

**Comment by jasl** [comment]
@chloerei 在哪...
我查了下生产环境的代码，确实是 `https://mapi.alipay.com/gateway.do` 不确定是之后API升级，我一会测试一下

**Comment by chloerei** [comment]
我见文档页没写网关地址，就在这 https://openhome.alipay.com/doc/docIndex.htm?url=https://openhome.alipay.com/doc/toSdk.htm 下载 php sdk，aop/AopClient.php 里面写有网关地址。

**Comment by jasl** [comment]
来review一下，测试用例都通过了

**Comment by chloerei** [comment]
我修改了一下参数名，str -> string，我不喜欢缩写。

**Comment by chloerei** [comment]
为了测试 RSA 校验，我已经实现了 RSA 签名了。

有一处修改，为了支持多帐号使用，RSA.sign 加了个 key 参数。统一起见 MD5.sign 也加上 key 参数。

**Comment by chloerei** [comment]
啊，我想起个问题。支付宝 WAP 的 RSA/DSA 公钥是不同的，所以公钥还得移出 Sign::RSA 模块。

**Comment by HungYuHei** [comment]
:+1: 代码差不多成型之后我到时可以帮忙在实际环境中测试一下。另外，版本是不是直接跳到 1.0.0 更适合呢？

**Comment by chloerei** [comment]
@HungYuHei 0.x 有个特权是 API 可以不兼容，如果这次新版稳定了就可以考虑 1.0 了。

**Comment by jasl** [comment]
`MD5.sign("#{params_to_string(params)}#{key}")` 这样写就可以了吧？在想`sign`函数只负责签名传入的字符串，其他的交给外部（如`Alipay::Sign`）来处理，是不是更遵循单一职责原则？

**Comment by chloerei** [comment]
这样：

```ruby
MD5.sign(string)
RSA.sign(key, string)
```

不协调。他们职责是：根据 key 和 string 生成签名。

**Comment by jasl** [comment]
也好
