### ISSUE TITLE
录制本 Gem 的使用视频

### ISSUE THREAD

**Issue by happypeter** [chloerei/alipay#31]
Hi Rei,

可能你还记得，我录制过一本支付宝站内集成的课程：http://haoqicat.com/happypeter/zhi-fu-bao-shou-kuan-ji-cheng 一年来卖了30来个拷贝。我觉得挺高兴，不过最近我这套课程需要更新了，因为支付宝下线了“双功能”接口，而我的课程中是以双功能为核心来讲的。用的 Gem 是我参考你和大庆的项目自己拼凑的 alipay_dualfun 。

最近的改进版中，我打算完全按照你的这个 Gem 来讲，我会

- 当然课程还是会收费的，但是我会开放40%的内容出来，开放的内容中会提及 Gem 的作者出处
- 不知道你对课程的内容安排有没有什么建议？
- 可否在本 Gem 的 Readme 或者其他地方给我的课程挂一个链接？
- 课程收入的 20% 会分成给你，因为使用你的 Gem 相当于你是课程的共同作者了

不知道大牛你意下如何？

**Comment by chloerei** [comment]
我不需要分成，对于这个课程我没有付出劳动，如果愿意可以提一下我的个人捐赠方式 http://chloerei.com/donate/ 。

到时我在 wiki 里面放链接吧。

**Comment by happypeter** [comment]
万分感谢！
