### ISSUE TITLE
seller_email 并非必填参数

### ISSUE THREAD

**Issue by x-ji** [chloerei/alipay#32]
开发者文档中说明，seller_email 和 seller_id 两者填一个即可。email 并非必填参数，而且有的账户并没有 email。如果我在Rails起始时候不载入 `Alipay.seller_email` 的话，这个 gem 仍然会试图在参数中加入 `&seller_email=''`。空参数会在阿里侧造成签名错误，也就是 `ILLEGAL_SIGN` 错误。希望如果使用者没有给 `Alipay.seller_email`赋值的话，在发出请求时不要包括它。

**Comment by x-ji** [comment]
还有就是现在我要如何把这个值从生成的 URL 中去掉

**Comment by chloerei** [comment]
支付宝各个接口非常不统一，有的必须有的不必须，例如担保交易是必须的：

![8](https://cloud.githubusercontent.com/assets/49931/7017842/fc2c4972-dd2f-11e4-92c4-7aceb96bfe6a.png)

你说的是哪个接口？在修复前可以打个 monkey patch 覆盖对应的方法。

**Comment by x-ji** [comment]
他说的是“两者必填一个”吧... 那个“是否为可空”是有点乱的 事实上应该是 seller_email 和 seller_id 两者之中一个填了另一个就可空 按道理如果有了 seller_id 的确没有必要再填写 seller_email 了

**Comment by chloerei** [comment]
担保交易接口吗？

**Comment by x-ji** [comment]
对的

**Comment by chloerei** [comment]
我正在尝试去掉所有 seller_email 参数，换用 seller_id 。

**Comment by chloerei** [comment]
试试 master 分支，已经去掉了 seller_email，用 seller_id 代替。

**Comment by x-ji** [comment]
嗯。应该可以了。总之在 `alipay.rb` 里面去掉 `Alipay.seller_email` 运行起来没有问题

**Comment by chloerei** [comment]
那我发布 0.7.0 版本。
