### ISSUE TITLE
Any demo for "境外收单" ？

### ISSUE THREAD

**Issue by tylerlong** [chloerei/alipay#33]
目前有需求向外国人出售软件产品。经过调查认为支付宝只支持人民币。 我看到这个gem的文档，提到境外收单。想了解下支付宝是可以实现美元收款的吗？还有是否支持国外的visa，master card等等支付方式？
问题可能跟技术无关哈。 如果有一个运行中的例子就最好了，一看便知。

**Comment by chloerei** [comment]
我没有这个接口权限，调试不了所以没写，我也希望有人能贡献一个 demo。

**Comment by tylerlong** [comment]
![screen shot 2015-04-07 at 3 31 07 pm](https://cloud.githubusercontent.com/assets/733544/7018777/2dc35dd0-dd3b-11e4-8759-066e178b6ec6.png)

**Comment by tylerlong** [comment]
![screen shot 2015-04-07 at 3 56 54 pm](https://cloud.githubusercontent.com/assets/733544/7019094/df053dc2-dd3e-11e4-8a90-89ba1eac09a1.png)

**Comment by chloerei** [comment]
收国外的钱用 paypal 或者 stripe 更好。

**Comment by tylerlong** [comment]
stripe不支持国内商户。 Paypal应该可以。 支付宝可以当然最好了。

**Comment by chloerei** [comment]
国外消费者对支付宝不熟悉。

**Comment by tylerlong** [comment]
经过调查，对支付宝针对国外消费者收款基本放弃。 咨询官方，他们也是支支吾吾，说明这方面尚无成熟可用解决方案。

**Comment by jimhj** [comment]
首先你需要申请一个支付宝的境外商户，其他的基本是一样的，这个文档我提供给了 @chloerei 。
需要注意的是，支付宝发送的notify 不会提供交易发生时的汇率。
