### ISSUE TITLE
NoMethodError (undefined method `auth_and_execute' for Alipay::Wap::Service:Module):

### ISSUE THREAD

**Issue by 85636682** [chloerei/alipay#36]
使用wap支付接口出现
NoMethodError (undefined method `auth_and_execute' for Alipay::Wap::Service:Module):
版本：0.7.1
rails 4.2

**Comment by chloerei** [comment]
`auth_and_execute_url` 文档错了。

**Comment by 85636682** [comment]
@chloerei 原来如此，好的，谢谢
