### ISSUE TITLE
MD5校验用的key和RSA校验用的key应该拆开

### ISSUE THREAD

**Issue by jasl** [chloerei/alipay#37]
RT，在我们的系统里，浏览器里的一般调用使用了MD5方式签名，但APP必须使用RSA方式签名，是不是分成`md5_key`和`rsa_key`更合适？
（最近工作比较紧，先提一下建议看看意见）

**Comment by chloerei** [comment]
可以使用第二个参数：

```
Alipay::Service.method?(params, { sign_type: 'MD5', key: '...'})
Alipay::Service.method?(params, { sign_type: 'RSA', key: '...'})
```

校验方法也支持第二个参数，但 sign_type 是根据校验参数定的，只有 MD5 需要换 key，RSA 用的是支付宝公钥不变。

**Comment by jasl** [comment]
是在说私钥，用于签名时候用

**Comment by chloerei** [comment]
私钥也是这么传。

**Comment by jasl** [comment]
我考虑下，如果要这么做的话，我可能还会在alipay的initializer里加载私钥，方便集中管理，最后可能会变成monkey patch进Alipay的命名空间，然后使用的时候去传key: Alipay::rsa_key

**Comment by chloerei** [comment]
常量不就行了？

**Comment by jasl** [comment]
可以呀 `ALIPAY_RSA_KEY`，原则上我尽量不在全局做事情

**Comment by chloerei** [comment]
于是我觉得维持现状就行了，我也在用两个 key，不过两个都是 MD5 的。

**Comment by jasl** [comment]
ok
