### ISSUE TITLE
网银支付

### ISSUE THREAD

**Issue by littlell** [chloerei/alipay#38]
支付宝网银支付的功能有集成吗？

**Comment by chloerei** [comment]
之前还没有人用过这个接口。我看了下文档，和即时到帐是用同一个接口（create_direct_pay_by_user），但是必填参数项不同。你可以试着用 `Alipay::Service.create_direct_pay_by_user_url` 看看。

**Comment by littlell** [comment]
OK， 是的， 唯一的区别就是*defaultbank*这个参数,  代表银行代号，  其余必选参数都是一样的。
