### ISSUE TITLE
关于支付宝移动支付RSA疑问

### ISSUE THREAD

**Issue by zhangcaiyan** [chloerei/alipay#42]
朋友，支付宝移动网站支付要用RSA，我看了你写的这部分获取sign的代码，用这个生成的sign还是无法发起支付宝支付

def self.sign(key, string)
    sa = OpenSSL::PKey::RSA.new(key)
    Base64.encode64(rsa.sign('sha1', string))
end

**Comment by chloerei** [comment]
你的代码是怎么写的？调用接口已经封装好方法了，不需要自己生成签名 https://github.com/chloerei/alipay/blob/master/lib/alipay/wap/service.rb

**Comment by chloerei** [comment]
因为没有新的反馈，所以关闭这个 issues。
