### ISSUE TITLE
如何设置alipay RSA

### ISSUE THREAD

**Issue by zben** [chloerei/alipay#44]
我的理解是移动支付需要RSA sign_type。需要自己生成private key 和 public key. public key需要上传给支付宝网站，private key怎么提供给request呢？可能我的理解有误，希望可以简单介绍一下怎么在这个gem里设置和使用RSA这个sign type。

**Comment by chloerei** [comment]
方法 1，全局：

```ruby
Alipay.key = '...'
Alipay.sign_type = 'RSA'
```

方法 2，一次性：

```ruby
Alipay.mobile_security_pay_url({ ... }, { key: '...', sign_type: 'RSA' }) 
```

**Comment by zben** [comment]
谢谢！

**Comment by chloerei** [comment]
注意别把 key 提交进代码库。
