### ISSUE TITLE
确认发货接口

### ISSUE THREAD

**Issue by happypeter** [chloerei/alipay#45]
hi @chloerei ，支付宝官方的 pdf 和你的 README 中，下面的接口都只需要两个参数就行了

```
Alipay::Service.send_goods_confirm_by_platform(
  trade_no: '201504010000001',
  logistics_name: 'example.com'
)
```

但是我实际测了一下，必须要加上 `:transport_type => 'DIRECT'` 才可以成功。

我觉得是支付宝那边的一个 bug ，你觉得呢？

**Comment by happypeter** [comment]
如果我的测试结果没有问题的话，建议在 README 中标明一下这个问题。让后面用 gem 的人少踩一个雷

**Comment by chloerei** [comment]
![alipay9](https://cloud.githubusercontent.com/assets/49931/8447538/07ac6a20-1fed-11e5-9dc0-64c587821d7b.png)
你说得对，这个字段跟另一个字段“不能同时为空”。我自己的代码加了，写文档的时候单看着支付宝文档然后漏掉了。

**Comment by happypeter** [comment]
cool
