### ISSUE TITLE
支付宝收款集成课程

### ISSUE THREAD

**Issue by happypeter** [chloerei/alipay#47]
Hi Rei,

前面跟你沟通过的，我的支付宝收款集成课程：http://haoqicat.com/happypeter/zhi-fu-bao-shou-kuan-ji-cheng 已经更新完毕。新版中全部代码都是围绕你的 alipay gem ，感谢你的劳动。

如果方便的话，请把课程链接加到本项目的某个地方，方便大家找到。另外，欢迎你对课程提出意见，我会继续改进的。谢谢！

![fb27cca3f20](https://cloud.githubusercontent.com/assets/72467/8514089/0e49219c-23b8-11e5-9bea-7160fcea051e.png)

**Comment by chloerei** [comment]
我加到了 wiki 中 https://github.com/chloerei/alipay/wiki

**Comment by happypeter** [comment]
万分感谢！
