### ISSUE TITLE
请问下手机网站支付用那个接口，是否实现?

### ISSUE THREAD

**Issue by boostbob** [chloerei/alipay#48]
手机网站支付alipay sdk文档的服务名称是alipay.wap.create.direct.pay.by.user.
谢谢~~

**Comment by chloerei** [comment]
目前还没有。我看了一下文档，之前的手机接口文档 `alipay.wap.trade.create.direct` 不见了，这个 `alipay.wap.create.direct.pay.by.user` 是新的。

我没有申请这个接口，也无法调试，所以最好你自己尝试写，参考 `/lib/alipay/service.rb` 里面的实现。

cc @HungYuHei @jasl 你们用到这个接口吗？

**Comment by HungYuHei** [comment]
我也没有用到

**Comment by jasl** [comment]
我们用的是移动快捷支付
`
Alipay::Service::Wap.trade_create_direct_token
Alipay::Service::Wap.auth_and_execute
`
这两个，这个需要申请的

**Comment by chloerei** [comment]
Wap 模块下的接口我在支付宝网站找不到注册页面和文档了，是不是要淘汰了，有没有收到通知？

**Comment by boostbob** [comment]
谢谢哈，我参考 `/lib/alipay/service.rb`搞一搞，wap估计真的是要被淘汰了.

**Comment by chloerei** [comment]
@jasl `Alipay::Service::Wap` 下的功能还能用吗？

**Comment by denny2trasy** [comment]
/lib/alipay/service.rb中的 Alipay::Service.create_direct_pay_by_user_wap_url 这个方法貌似不能用，对吗？

**Comment by chloerei** [comment]
@denny2trasy 这是最新添加的，还没发布到 gem，可以用 master 分支测试。
