### ISSUE TITLE
Unmatched method name between source code and doc

### ISSUE THREAD

**Issue by serco-chen** [chloerei/alipay#51]
lib/alipay/mobile/service.rb line 5 `mobile_securitypay_pay_string`
readme `mobile_security_pay_string `

**Comment by serco-chen** [comment]
@chloerei Not sure which one is your originally desired method name.

**Comment by chloerei** [comment]
`mobile_securitypay_pay_string`, same with service name `mobile.securitypay.pay`.

**Comment by serco-chen** [comment]
@chloerei Then update the readme please.
