### ISSUE TITLE
APP支付还支持吗？

### ISSUE THREAD

**Issue by FX-HAO** [chloerei/alipay#63]
我发现文档要求的请求参数和签名返回的参数有些不一致， 能帮忙检查一下吗？

[App支付请求参数说明](https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.HPTQi3&treeId=204&articleId=105465&docType=1)

**Comment by chloerei** [comment]
可以把文档链接发一下。
Fuxin Hao <notifications@github.com>于2016年12月6日 周二14:07写道：

**Comment by FX-HAO** [comment]
@chloerei  https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.HPTQi3&treeId=204&articleId=105465&docType=1

**Comment by FX-HAO** [comment]
我理解的是通过调用`Alipay::Mobile::Service.mobile_securitypay_pay_string`， 把返回的数据传给app端， app端不能修改参数(否则sign就无效了)，app端用返回的参数直接调支付宝客户端sdk。

但现在我发现签名返回的数据与[支付宝文档](https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.HPTQi3&treeId=204&articleId=105465&docType=1)的请求参数很多都对不上(比如文档中的biz_content和app_id而不是seller_id)， 不知道我的理解是否有误？

**Comment by FX-HAO** [comment]
我理解错了， 这个库只支持移动支付， 还没有APP支付。

我自己实现了APP支付的功能， 介意我提个PR吗 :P

**Comment by chloerei** [comment]
可以啊。
Fuxin Hao <notifications@github.com>于2016年12月22日 周四11:44写道：
