### ISSUE TITLE
App支付返回的参数，验证失败

### ISSUE THREAD

**Issue by rocLv** [chloerei/alipay#67]
返回的参数验证失败，不知道大家的都正常吗？

**Comment by mysterytree** [comment]
@rocLv 兄弟你最后怎么解决的

**Comment by yanchengv** [comment]
@rocLv @mysterytree 我用的新接口，验签也失败，你们解决了吗

**Comment by chloerei** [comment]
提供细节，用的什么接口，返回什么信息。

**Comment by hanyong37** [comment]
新版支付宝接口和老板对比，返回参数有很多不同的地方： https://doc.open.alipay.com/docs/doc.htm?docType=1&articleId=106759  --目前这个gem只支持老版本接口吧？

**Comment by yanchengv** [comment]
如果用新版接口的需要自己写，后来借鉴本gem我又重新写的

**Comment by mysterytree** [comment]
我也是自己写的。。

**Comment by dulao5** [comment]
我做了支持 app 支付 / rsa2 的Pull request  :  https://github.com/chloerei/alipay/pull/69

**Comment by yanchengv** [comment]
我写了一个支持支付宝2017接口的gem, rsa2。`gem my_alipay`,[gem仓库地址](https://github.com/yanchengv/my_alipay)

**Comment by chloerei** [comment]
已经合并了 #69 ，麻烦楼上诸位帮测试 master 分支。

**Comment by feng88724** [comment]
谢谢各位的付出。

目前master分支已经是最新版，包括文档，已经写了支持rsa2。但当前Gem版本还是0.14.0，也就是尚不支持rsa2的。造成了一些困扰。

V0.14.0和当前文档描述差异：
1、APP支付，下单尚不支持rsa2
2、支付宝回调，验证参数尚不支持options参数

**Comment by chloerei** [comment]
Master 有足够反馈就会发新版
幻影浪子 <notifications@github.com>于2017年6月16日 周五15:14写道：

**Comment by ly123525** [comment]
我要的RAS,也不好使啊!

**Comment by chloerei** [comment]
欢迎测试新版 API https://github.com/chloerei/alipay/issues/70

要注意的是，https://github.com/chloerei/alipay/pull/69 新增的 Alipay::App 模块被删除（未正式发布），因为已经被新 API 覆盖到。

**Comment by ly123525** [comment]
创建交易异常,请重新创建后再付款!

**Comment by chloerei** [comment]
0.15.0 release, stop adding feature to old api.

https://github.com/chloerei/alipay/blob/master/CHANGELOG.md#v0150-2017-08-27
