### ISSUE TITLE
新版支付宝API支持

### ISSUE THREAD

**Issue by ryancheung** [chloerei/alipay#70]
新支付网关 `https://openapi.alipay.com/gateway.do` 下API支持

**Comment by chloerei** [comment]
新版 API 正在 openapi 分支开发 https://github.com/chloerei/alipay/tree/openapi

新版 API 模式比较统一，不需要像旧版那样每个 API 都添加一个方法，只要提供几个 API 就行。详情看代码注释 https://github.com/chloerei/alipay/blob/openapi/lib/alipay/client.rb

欢迎测试和贡献。

**Comment by zlx** [comment]
看上去新的 API 需要提供接口名字以及对应参数，不确定这样对用户来说是否更方便了。

新版接口可以保证接口统一，也更加方便扩展，这样做对于频繁变化的接口来说无可厚非，实际上也有很多大公司采用这种做法，如亚马逊，google 等。

但是对于实际开发人员来说，在接入时，需要熟悉客户端和官方 API，这无疑增加了接入的成本。

**Comment by chloerei** [comment]
官方文档是一定要看的，gem 方法命名尽量跟官方 sdk 一致，这样就好理解。
Newell Zhu <notifications@github.com>于2017年7月3日 周一13:15写道：

**Comment by agilejzl** [comment]
呀，没等这个新版本出来，自己前一阵子在老版本集成了新网关的部分接口，混在一起，同时加上了 RSA2签名。

**Comment by FrankFang** [comment]
我用了一下新版，挺流畅的。
支付宝终于告别 XML 了。
Your gem is just awesome!

**Comment by chloerei** [comment]
0.15.0 release, stop adding feature to old api.

https://github.com/chloerei/alipay/blob/master/CHANGELOG.md#v0150-2017-08-27

**Comment by FrankFang** [comment]
@chloerei  旧版不维护了？
No support for old API anymore?

**Comment by chloerei** [comment]
不增加新特性
Frank Fang <notifications@github.com>于2017年8月28日 周一01:02写道：
