### ISSUE TITLE
wap 支付，呼出支付宝客户端

### ISSUE THREAD

**Issue by shopshow** [chloerei/alipay#73]
在支付参数中加入 app_pay: 'Y', 如手机已安装支付宝客户端，浏览器会提示是否呼出客户端支付。
亲测 create_forex_trade_wap 有效，可否在文档添加此处说明，毕竟 native支付要比网页支付体验好的多

**Comment by chloerei** [comment]
0.15.0 release, stop adding feature to old api.

https://github.com/chloerei/alipay/blob/master/CHANGELOG.md#v0150-2017-08-27
