### ISSUE TITLE
请问有芝麻认证相关接口吗？

### ISSUE THREAD

**Issue by FrankFang** [chloerei/alipay#87]

**Comment by chloerei** [comment]
没接触过呢。现在 `Alipay::Client` 这个类里只有几个通用方法，根据参数不同可以调用不同的支付宝接口。如果芝麻认证跟支付宝是同样的 endpoint 和调用模式就可以用。

阿里系的接口太过繁杂又不统一，不会像以前那样每个接口都写一个对应的 ruby 方法。
