### ISSUE TITLE
回调notify_url参数无效

### ISSUE THREAD

**Issue by zhuangbifanisme** [chloerei/alipay#88]
`
    @alipay_client.page_execute_url(
        method: AlipayScan::Interface::TradePagePay,
        biz_content: JSON.generate({
                                       out_trade_no: '1234567891112',
                                       product_code: 'FAST_INSTANT_TRADE_PAY',
                                       total_amount: '0.01',
                                       subject: '测试一下',
                                       qr_pay_mode: 4,
                                   }, ascii_only: true), 
        timestamp: Time.now.strftime('%Y-%m-%d %H:%M:%S'),
        notify_url: "#{::HostSetting.domain}/pay/alipays/alipay_scan_code_notify",

        )`
扫码支付成功后 不通知notify_url的地址，请问支持notify_url参数吗。

**Comment by chloerei** [comment]
支持的，notify_url 加上 `http://` 或者 `https://` 看看。

**Comment by zhuangbifanisme** [comment]
好的，多谢。
