### ISSUE TITLE
请问app支付可以用么？

### ISSUE THREAD

**Issue by GuanMinjie** [chloerei/alipay#89]
如题： 我在使用alipay.trade.app.pay 时， 传过 app_id依旧，返回错误提示 “缺少app_id”, 。 请问这个gem支付app支付吗

**Comment by chloerei** [comment]
不确定，我没实际用过。把敏感信息剔除，贴一下代码。

**Comment by GuanMinjie** [comment]
client.page_execute_url(
        method: 'alipay.trade.app.pay',
        notify_url: 'http://domea/api/v1/orders/notify',
        biz_content: JSON.generate({
          body: "景维三维重建服务",
          subject: '重建服务费',
          out_trade_no: self.trade_no,
          product_code: 'QUICK_MSECURITY_PAY',         
          total_amount: self.amount     
        }, ascii_only: true)
      )

**Comment by GuanMinjie** [comment]
notify_url 的值是修改过的  假接口

**Comment by GuanMinjie** [comment]
def client
  		Alipay::Client.new(
  			url: API_URL,
  			app_id: APP_ID,
  			app_private_key: APP_PRIVATE_KEY,
  			alipay_public_key: ALIPAY_PUBLIC_KEY
		)
  	end

**Comment by GuanMinjie** [comment]
在调用 网页端支付的时候是没问题的

**Comment by chloerei** [comment]
用 alipay.trade.app.pay 的整个流程是怎么样的，需要服务端还是客户端发起请求，能不能发一下 alipay 的文档链接，我太久没碰已经搞不清楚了。

**Comment by GuanMinjie** [comment]
https://docs.open.alipay.com/204/105297/

**Comment by chloerei** [comment]
要处理的是不是第2，3步？

![LB1uQPIPVXXXXbAXpXXXXXXXXXX](https://user-images.githubusercontent.com/49931/58150531-7e297f00-7c99-11e9-9c28-028ce98d703c.png)

好像应该用这个方法：
https://github.com/chloerei/alipay/blob/master/lib/alipay/client.rb#L42-L61

**Comment by GuanMinjie** [comment]
谢谢  之前没 看到这个方法  我去试一下

**Comment by GuanMinjie** [comment]
请问为什么这个方法 返回是queryString 而不是 一个 url呢？ 还是说 这样设计有什么特别之处吗？

**Comment by chloerei** [comment]
这个 queryString 是给移动端 SDK 用的吧，移动端计算签名不安全，实际上是让服务端帮签名一次。

**Comment by GuanMinjie** [comment]
实验证明  "https://openapi.alipay.com/gateway.do?"+query_string  的结果和    client.page_execute_url 中method： 'alipay.trade.app.pay' 的结果是一样的。   

我这样做是因为 我在 APP调用支付的时候 需要的是  "https://openapi.alipay.com/gateway.do?"+query_string   这样的一个url形式的

**Comment by chloerei** [comment]
是一样的，看源码也可以看出来。

**Comment by GuanMinjie** [comment]
也是  那这样问题又回到原来的问题了 目前还是  同样的报错 ， 提示说 确实 app_id  但是我看结果中 是有 app_id的

**Comment by GuanMinjie** [comment]
提示说 缺少 app_id

**Comment by chloerei** [comment]
那我也不知道了。

**Comment by GuanMinjie** [comment]
我再去 支付宝中 找找问题吧   谢谢您的回复

**Comment by GuanMinjie** [comment]
gem本身没有任何问题  支持 app支付
经过一些折腾  我发现是我理解错了 移动端 sdk的用法  错误的认为需要将 网关 和  query_string 组合成一个url进行传递

**Comment by chloerei** [comment]
👍
