### ISSUE TITLE
开放平台证书升级

### ISSUE THREAD

**Issue by moohao** [chloerei/alipay#91]
![image](https://user-images.githubusercontent.com/32318384/63759935-f5059200-c8f0-11e9-842e-091a2c525f49.png)

好像现在公钥的方式不支持转账了，需要使用公钥证书的方式。

**Comment by chloerei** [comment]
由于我现在没有应用在用支付宝，很难开发调试新特性，欢迎提交 PR。

**Comment by moohao** [comment]
> 由于我现在没有应用在用支付宝，很难开发调试新特性，欢迎提交 PR。

已经提交了PR😁

**Comment by chloerei** [comment]
Closed by #92
