### ISSUE TITLE
扫码支付回调会报 ActionController::BadRequest 的错，发现返回的回调中的编码是 GBK

### ISSUE THREAD

**Issue by otorain** [chloerei/alipay#93]
回调中报错：ActionController::BadRequest (Invalid request parameters: Invalid encoding for parameter: ���Ų����ײ�)。
试着加入中间件拦截后发现回调中的 charset 是 GBK。可能是我的 subject 参数是中文的原因

目前解决方案是在网关地址后面加 `?charset=UTF-8`
```ruby
@client = Alipay::Client.new(
  url: "https://openapi.alipay.com/gateway.do?charset=UTF-8",
  app_id: APP_ID,
  app_private_key: APP_PRIVATE_KEY,
  alipay_public_key: ALIPAY_PUBLIC_KEY
)
```

**Comment by cisolarix** [comment]
URL 末尾加 ?charset=UTF-8 看起来是正解。
